function init(self)
  self.btn_sound_on = true
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
  	msg.post(".", "acquire_input_focus") -- Acquire input focus for this game object
end


function on_input(self, action_id, action)
	if action_id == hash("touch") and  action.pressed then  --not action.pressed
		local button_play = gui.get_node("PLAY") 
    local button_sound = gui.get_node("SOUND_ON_OFF")
      
		if gui.pick_node(button_play, action.x, action.y) then
     print("PLAY button pressed")
     msg.post("main:/collections_loader#collections_loader", "start_game")   
		end

    if gui.pick_node(button_sound, action.x, action.y) then    
   -- local button_sound = gui.get_node("SOUND_ON_OFF") 
     if self.btn_sound_on then
        gui.play_flipbook(button_sound, hash("Sound_OFF"))  
        self.btn_sound_on = false
        else 
        gui.play_flipbook(button_sound, hash("Sound_ON"))  
        self.btn_sound_on = true
     end
    end
  
  end
end
