function init(self)
    msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
    if action_id == hash("touch") and action.pressed then
        local play_btn = gui.get_node("play_button")
        if gui.pick_node(play_btn, action.x, action.y) then
            print("PLAY button pressed")
            msg.post("main:/collections_loader#collections_loader", "menu_game")
        end
    end
end